SchoolWeb/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include

from account.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^admini/', include('admini.urls')),
    url(r'^encargado/', include('encargado.urls')),
    url(r'^message/', include('message.urls')),
     url(r'^events/', include('events.urls')),
    url(r'^secretaria/', include('secretaria.urls')),
    url(r'^docente/', include('docente.urls')),
    url(r'^$', index, name='form_login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admini/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^year/new/$', views.new_year, name='new_year'),
	url(r'^year/new/add/$', views.new_year_add, name='new_year_add'),
	url(r'^year/all/$', views.all_years, name='all_years'),
	url(r'^grade/new/$', views.new_grade, name='new_grade'),
	url(r'^grade/new/add/$', views.new_grade_add, name='new_grade_add'),
	url(r'^grade/edit/(?P<pk>\d+)/$', views.edit_grade, name='edit_grade'),
	url(r'^grade/all/$', views.all_grades, name='all_grades'),
	url(r'^section/new/$', views.new_section, name='new_section'),
	url(r'^section/new/add/$', views.new_section_add, name='new_section_add'),
	url(r'^section/edit/(?P<pk>\d+)/$', views.edit_section, name='edit_section'),
	url(r'^section/all/$', views.all_sections, name='all_sections'),
	url(r'^class/new/$', views.new_class, name='new_class'),
	url(r'^class/new/add/$', views.new_class_add, name='new_class_add'),
	url(r'^class/all/$', views.all_classes, name='all_classes'),
	url(r'^class/edit/(?P<pk>\d+)/$', views.edit_class, name='edit_class'),
	url(r'^grade_section/new/$', views.new_grade_section, name='new_grade_section'),
	url(r'^grade_section/new/add/$', views.new_grade_section_add, name='new_grade_section_add'),
	url(r'^grade_section/all/$', views.all_grades_section, name='all_grades_section'),
	url(r'^grade_class/new/$', views.new_grade_class, name='new_grade_class'),
	url(r'^grade_class/new/add/$', views.new_grade_class_add, name='new_grade_class_add'),
	url(r'^grade_offer/new/$', views.offer_new_grade, name='offer_new_grade'),
	url(r'^grade_offer/new/add/$', views.new_grade_offer_add, name='new_grade_offer_add'),
	url(r'^grade_offer/all/$', views.all_grades_offer, name='all_grades_offer'),
	url(r'^class_offer/new/$', views.offer_new_class, name='offer_new_class'),
	url(r'^class_offer/all/$', views.all_classes_offer, name='all_classes_offer'),
	url(r'^enroll/new/$', views.new_enroll, name='new_enroll'),
	url(r'^enroll/massive/$', views.enroll_massive, name='enroll_massive'),
	url(r'^enroll/massive/add/$', views.enroll_massive, name='enroll_massive'),
	url(r'^enroll/all/$', views.all_enroll, name='all_enroll'),
	url(r'^enroll/new/add/$', views.new_enroll_add, name='new_enroll_add'),
	url(r'^student/new/$', views.new_student, name='new_student'),
	url(r'^student/all/$', views.all_students, name='all_students'),
	url(r'^workposition/new/$', views.new_workposition, name='new_workposition'),
	url(r'^workposition/all/$', views.all_workpositions, name='all_workpositions'),
	url(r'^employee/new/$', views.new_employee, name='new_employee'),
	url(r'^employee/all/$', views.all_employees, name='all_employees'),
	url(r'^user/new/$', views.new_user, name='new_user'),
	url(r'^user/all/$', views.all_users, name='all_users'),
	url(r'^tutor/all/$', views.all_tutors, name='all_tutors'),
	url(r'^tutor/new/$', views.new_tutor, name='new_tutor'),
	url(r'^grade/(?P<pk>\d+)/sections/$', views.sections_by_grade, name='sections_by_grade'),
	url(r'^grade/(?P<pk>\d+)/classes/$', views.classes_by_grade, name='classes_by_grade'),
	url(r'^grade_offer/current/$', views.current_grades_offer, name='current_grades_offer'),
	url(r'^class_offer/current/$', views.current_classes_offer, name='current_classes_offer'),
	url(r'^enroll/current/$', views.current_enroll, name='current_enroll'),
	url(r'^settings/$', views.settings, name='settings'),
	url(r'^settings/save/$', views.settings_save, name='settings_save'),
	url(r'^reports/$', views.reports, name='reports'),
	url(r'^reports/historial/$', views.reports_historial, name='reports_historial'),
	url(r'^reports/historial/(?P<pk>\d+)/$', views.reports_historial_bystudent, name='reports_historial_bystudent'),
	url(r'^reports/studentlist/$', views.reports_studentlist, name='reports_bystudentlist'),
	url(r'^reports/studentlist/(?P<pk>\d+)/$', views.reports_studentlist_bygrade, name='reports_studentlist_bygrade'),

]

message/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^bandeja/$', views.msg_index, name='msg_index'),
	url(r'^enviados/$', views.msg_enviados, name='msg_enviados'),
	url(r'^new/$', views.msg_new, name='msg_new'),
	url(r'^delete/(?P<pk>\d+)/$', views.msg_delete, name='msg_delete'),
	url(r'^read/(?P<pk>\d+)/$', views.msg_read, name='msg_read'),
]

message/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Mensaje(models.Model):
	remitente = models.ForeignKey(User, related_name='fromuser')
	asunto =  models.CharField(max_length=50)
	contenido = models.TextField()
	destinatario = models.ForeignKey(User, related_name='touser')
	leido = models.BooleanField(default=False)
	archivo = models.FileField(upload_to="media/message", blank=True,null=True)
	fecha = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	def __unicode__(self):
		return unicode(self.asunto)

message/forms.py
from django import forms
from .models import Mensaje

class MensajeForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = '__all__'
        widgets = {'remitente': forms.HiddenInput(),'leido': forms.HiddenInput()}

message/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import MensajeForm

from django.contrib.auth.models import User
from .models import *
def msg_index(request):
	form = MensajeForm(initial={'remitente': request.user, 'leido': False})
	users = User.objects.all()
	msjsr = Mensaje.objects.filter(destinatario= request.user).order_by('-fecha')
	total = msjsr.count()
	if request.user.Perfil.es_admin:
		return render(request, 'msg_index.html', {'msjsr':msjsr, 'users':users, 'total': total, 'form': form})
	elif request.user.Perfil.es_secre:
		return render(request, 'msg_index_secre.html', {'msjsr':msjsr, 'users':users, 'total': total, 'form': form})
	elif request.user.Perfil.es_docente:
		return render(request, 'msg_index_docente.html', {'msjsr':msjsr, 'users':users, 'total': total, 'form': form})
	elif request.user.Perfil.es_tutor:
		return render(request, 'msg_index_encargado.html', {'msjsr':msjsr, 'users':users, 'total': total, 'form': form})

def msg_enviados(request):
	form = MensajeForm(initial={'remitente': request.user, 'leido': False})
	users = User.objects.all()
	msjse = Mensaje.objects.filter(remitente= request.user).order_by('-fecha')
	msjsr = Mensaje.objects.filter(destinatario= request.user).order_by('-fecha')
	total = msjsr.count()
	if request.user.Perfil.es_admin:
		return render(request, 'msg_send.html' ,{'msjse':msjse, 'users':users,'total': total, 'form': form})
	elif request.user.Perfil.es_secre:
		return render(request, 'msg_send_secre.html' ,{'msjse':msjse, 'users':users,'total': total, 'form': form})
	elif request.user.Perfil.es_docente:
		return render(request, 'msg_send_docente.html' ,{'msjse':msjse, 'users':users,'total': total, 'form': form})
	elif request.user.Perfil.es_tutor:
		return render(request, 'msg_send_encargado.html' ,{'msjse':msjse, 'users':users,'total': total, 'form': form})

def msg_new(request):
	if request.method == 'POST':
		form = MensajeForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/message/bandeja/')

@login_required()
def msg_delete(request, pk):
	msj = Mensaje.objects.get(pk=pk)
	try:
		msj.delete()
		return HttpResponseRedirect('/message/bandeja/')
	except Exception as e:
		return HttpResponse("")	

@login_required()
def msg_read(request, pk):
	msj = Mensaje.objects.get(pk=pk)
	try:
		msj.leido = True
		msj.save()
		return HttpResponse()
	except Exception as e:
		return HttpResponse()

message/templates/msg_index.html
{% extends "base_in_admin.html" %}

{% block info %}
<div class="container">
<div class="row container">
	<div class="col-md-11"><h3>Servicio de mensajeria</h3></div>
<div class="row container">
  <div class="col-md-3">
  <br>
    <a href="" data-toggle="modal" data-target="#new_msg" class="btn btn-primary btn-md btn-3d">Redactar</a>
    </div>

</div>
<br>
		<div class="row container">
        <div class="col-md-3 mail-left-content">
                               <ul class="nav">
                                <li></li>
                                  <li><br></li>
                                  <li><h5>Carpeta</h5></li>
                                  <li>
                                    <a href="{% url 'msg_index' %}" class="read"><span class="fa fa-inbox"></span> Recibidos ({{ total }})</a>
                                  </li>
                                  <li>
                                    <a href="{% url 'msg_enviados' %}"><span class="fa fa-send-o"></span> Enviados</a>
                                  </li>
                              </ul>
            </div>
            {% block msg %}
                                <div class="col-md-8 mail-right-content">
                   <table id="datatable" class="table table-hover" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th>Remitente</th>
                          <th>Asunto</th>
                          <th>Fecha</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for msj in msjsr  %}
                        {% if msj.leido == True %}
                          <tr>
                                  <td class="contact">
                                    {{ msj.remitente }}
                                    </td>
                                     <td class="subject">
                                     {{ msj.asunto }}
                                      </td>
                                      <td class="time"><span title="{{ msj.fecha }}">Hace {{ msj.fecha| timesince }}</span></td>
                                      <td>
                                                          <div class="btn-group">
                    <button class="dropdown-toggle btn btn-primary btn-3d btn-sm" data-toggle="dropdown" aria-expanded="true">Acciones &nbsp<span class="fa fa-caret-down"></span></button>
                    <ul class="dropdown-menu">
                      <li><a class="btn-leer" data-id="{{ msj.id }}" data-asunto="{{ msj }}"  data-contenido="{{ msj.contenido }}" data-remitente="{{ msj.remitente }}"
                      data-remitente-id="{{ msj.remitente.id }}" data-nombre-archivo="{{ msj.archivo.name }}" data-archivo="/media/{{ msj.archivo }}" data-toggle="modal" data-target="#view_msg">Leer<span class="fa fa-eye pull-left "></span></a></li>
                      <li><a class="" href="/message/delete/{{ msj.id }}/" data-id="" data-clase="">Eliminar<span class="fa fa-trash pull-left "></span></a></li>
                    </ul>
                  </div>
                                      </td>
                                  </tr>
                                  {% else %}
                                    <tr class="active">
                                  <td class="contact">
                                    {{ msj.remitente }}
                                    </td>
                                     <td class="subject">
                                     {{ msj.asunto }}
                                      </td>
                                      <td class="time"><span title="{{ msj.fecha }}">Hace {{ msj.fecha| timesince }}</span></td>
                                      <td>
                                                          <div class="btn-group">
                    <button class="dropdown-toggle btn btn-primary btn-3d btn-sm" data-toggle="dropdown" aria-expanded="true">Acciones &nbsp<span class="fa fa-caret-down"></span></button>
                    <ul class="dropdown-menu">
                      <li><a class="btn-leer" data-id="{{ msj.id }}" data-asunto="{{ msj }}"  data-contenido="{{ msj.contenido }}" data-remitente="{{ msj.remitente }}"
                      data-remitente-id="{{ msj.remitente.id }}" data-nombre-archivo="{{ msj.archivo.name }}" data-archivo="/media/{{ msj.archivo }}" data-toggle="modal" data-target="#view_msg">Leer<span class="fa fa-eye pull-left "></span></a></li>
                      <li><a class="" href="/message/delete/{{ msj.id }}/" data-id="" data-clase="">Eliminar<span class="fa fa-trash pull-left "></span></a></li>
                    </ul>
                  </div>
                                      </td>
                                  </tr>
                        {% endif %}

                      {% endfor %}
                                  </tbody>
                              </table>
                          </div>
            {% endblock %}

		</div>
    </div>

      <div class="modal fade" id="new_msg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Nuevo mensaje</h4>
      </div>
      <div class="modal-body">
        <form action="/message/new/" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.remitente }}
          <div class="form-group">
              <label for="destinatario">Destinatario</label>
                {{ form.destinatario }}
          </div>
                <div class="form-group form-animate-text" style="margin-top:40px !important;">
                    {{ form.asunto }}
                    <span class="bar"></span>
                    <label>Asunto</label>
                  </div>
                  <div class="form-group">
                   <label for="contenido">Contenido</label>
                   {{ form.contenido }}
                  </div>
                  {{ form.archivo }}
                <button type="button" class="btn btn-danger btn-3d" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
          <button type="submit" class="btn btn-success btn-3d btn-actualizar"><i class="fa fa-check"></i>Enviar</button>


        </form>
      </div>
  </div>
  </div>
</div>

<div class="modal fade" id="view_msg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4  id="modal-title" class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
        <form action="" method="post">
        {% csrf_token %}
                  <h4 id="asuntoo"></h4>
                  <hr>
                  <h5 id="contenidoo"></h5>
                  <hr>
                  <a id="archivo"></a>
        </form>
      </div>
  </div>
  </div>
</div>
	
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
    $('#id_destinatario').attr("multiple", 'multiple')
    $("#id_destinatario").select2({
      tags: true
    });

    $('#datatable').DataTable();
    $("#id_archivo").filestyle({input: false});
    $("#id_archivo").filestyle('size', 'sm');
    $("#id_archivo").filestyle('buttonName', 'btn-primary btn-md btn btn-3d');
    $("#id_archivo").filestyle('buttonText', 'Adjuntar archivo');
    $("#id_archivo").attr('data-iconName','fa fa-folder-open-o');;
    $(".icon-span-filestyle").removeClass('glyphicon glyphicon-folder-open')
    $(".icon-span-filestyle").addClass('fa fa-folder-open-o')
    $("#id_asunto").addClass('form-text')
    $("#id_contenido").addClass('form-control')
    $("#id_contenido").attr('rows', '4')

    $('.btn-leer').click(function(e)
    {
      e.preventDefault();
      var _asunto = $(this).attr('data-asunto');
      var _contenido = $(this).attr('data-contenido');
      var _remitente = $(this).attr('data-remitente');
      var _archivo = $(this).attr('data-archivo');
      var _nombre_archivo = $(this).attr('data-nombre-archivo');
      var _id = $(this).attr('data-id');
      $("#asuntoo").text("Asunto: " + _asunto);
      $("#contenidoo").text(_contenido) ;
      $("#modal-title").text("Mensaje de " + _remitente)
      $("#archivo").text(_nombre_archivo)
      $("#archivo").attr("href", _archivo)

        $.ajax({
          type:'GET',
          url:'/message/read/' + _id + "/",
        success: function(){
        }
      });

    });

  });
</script> 
{% endblock  %}

message/templates/msg_index_docente.html
{% extends "base_in_docente.html" %}

{% block info %}
<div class="container">
<div class="row container">
	<div class="col-md-11"><h3>Servicio de mensajeria</h3></div>
<div class="row container">
  <div class="col-md-3">
  <br>
    <a href="" data-toggle="modal" data-target="#new_msg" class="btn btn-primary btn-md btn-3d">Redactar</a>
    </div>

</div>
<br>
		<div class="row container">
        <div class="col-md-3 mail-left-content">
                               <ul class="nav">
                                <li></li>
                                  <li><br></li>
                                  <li><h5>Carpeta</h5></li>
                                  <li>
                                    <a href="{% url 'msg_index' %}" class="read"><span class="fa fa-inbox"></span> Recibidos ({{ total }})</a>
                                  </li>
                                  <li>
                                    <a href="{% url 'msg_enviados' %}"><span class="fa fa-send-o"></span> Enviados</a>
                                  </li>
                              </ul>
            </div>
            {% block msg %}
                                <div class="col-md-8 mail-right-content">
                   <table id="datatable" class="table table-hover" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th>Remitente</th>
                          <th>Asunto</th>
                          <th>Fecha</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for msj in msjsr  %}
                        {% if msj.leido == True %}
                          <tr>
                                  <td class="contact">
                                    {{ msj.remitente }}
                                    </td>
                                     <td class="subject">
                                     {{ msj.asunto }}
                                      </td>
                                      <td class="time"><span title="{{ msj.fecha }}">Hace {{ msj.fecha| timesince }}</span></td>
                                      <td>
                                                          <div class="btn-group">
                    <button class="dropdown-toggle btn btn-primary btn-3d btn-sm" data-toggle="dropdown" aria-expanded="true">Acciones &nbsp<span class="fa fa-caret-down"></span></button>
                    <ul class="dropdown-menu">
                      <li><a class="btn-leer" data-id="{{ msj.id }}" data-asunto="{{ msj }}"  data-contenido="{{ msj.contenido }}" data-remitente="{{ msj.remitente }}"
                      data-remitente-id="{{ msj.remitente.id }}" data-nombre-archivo="{{ msj.archivo.name }}" data-archivo="/media/{{ msj.archivo }}" data-toggle="modal" data-target="#view_msg">Leer<span class="fa fa-eye pull-left "></span></a></li>
                      <li><a class="" href="/message/delete/{{ msj.id }}/" data-id="" data-clase="">Eliminar<span class="fa fa-trash pull-left "></span></a></li>
                    </ul>
                  </div>
                                      </td>
                                  </tr>
                                  {% else %}
                                    <tr class="active">
                                  <td class="contact">
                                    {{ msj.remitente }}
                                    </td>
                                     <td class="subject">
                                     {{ msj.asunto }}
                                      </td>
                                      <td class="time"><span title="{{ msj.fecha }}">Hace {{ msj.fecha| timesince }}</span></td>
                                      <td>
                                                          <div class="btn-group">
                    <button class="dropdown-toggle btn btn-primary btn-3d btn-sm" data-toggle="dropdown" aria-expanded="true">Acciones &nbsp<span class="fa fa-caret-down"></span></button>
                    <ul class="dropdown-menu">
                      <li><a class="btn-leer" data-id="{{ msj.id }}" data-asunto="{{ msj }}"  data-contenido="{{ msj.contenido }}" data-remitente="{{ msj.remitente }}"
                      data-remitente-id="{{ msj.remitente.id }}" data-nombre-archivo="{{ msj.archivo.name }}" data-archivo="/media/{{ msj.archivo }}" data-toggle="modal" data-target="#view_msg">Leer<span class="fa fa-eye pull-left "></span></a></li>
                      <li><a class="" href="/message/delete/{{ msj.id }}/" data-id="" data-clase="">Eliminar<span class="fa fa-trash pull-left "></span></a></li>
                    </ul>
                  </div>
                                      </td>
                                  </tr>
                        {% endif %}

                      {% endfor %}
                                  </tbody>
                              </table>
                          </div>
            {% endblock %}

		</div>
    </div>

      <div class="modal fade" id="new_msg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Nuevo mensaje</h4>
      </div>
      <div class="modal-body">
        <form action="/message/new/" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.remitente }}
          <div class="form-group">
              <label for="destinatario">Destinatario</label>
                {{ form.destinatario }}
          </div>
                <div class="form-group form-animate-text" style="margin-top:40px !important;">
                    {{ form.asunto }}
                    <span class="bar"></span>
                    <label>Asunto</label>
                  </div>
                  <div class="form-group">
                   <label for="contenido">Contenido</label>
                   {{ form.contenido }}
                  </div>
                  {{ form.archivo }}
                <button type="button" class="btn btn-danger btn-3d" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
          <button type="submit" class="btn btn-success btn-3d btn-actualizar"><i class="fa fa-check"></i>Enviar</button>


        </form>
      </div>
  </div>
  </div>
</div>

<div class="modal fade" id="view_msg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4  id="modal-title" class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
        <form action="" method="post">
        {% csrf_token %}
                  <h4 id="asuntoo"></h4>
                  <hr>
                  <h5 id="contenidoo"></h5>
                  <hr>
                  <a id="archivo"></a>
        </form>
      </div>
  </div>
  </div>
</div>
	
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
    $('#id_destinatario').attr("multiple", 'multiple')
    $("#id_destinatario").select2({
      tags: true
    });

    $('#datatable').DataTable();
    $("#id_archivo").filestyle({input: false});
    $("#id_archivo").filestyle('size', 'sm');
    $("#id_archivo").filestyle('buttonName', 'btn-primary btn-md btn btn-3d');
    $("#id_archivo").filestyle('buttonText', 'Adjuntar archivo');
    $("#id_archivo").attr('data-iconName','fa fa-folder-open-o');;
    $(".icon-span-filestyle").removeClass('glyphicon glyphicon-folder-open')
    $(".icon-span-filestyle").addClass('fa fa-folder-open-o')
    $("#id_asunto").addClass('form-text')
    $("#id_contenido").addClass('form-control')
    $("#id_contenido").attr('rows', '4')

    $('.btn-leer').click(function(e)
    {
      e.preventDefault();
      var _asunto = $(this).attr('data-asunto');
      var _contenido = $(this).attr('data-contenido');
      var _remitente = $(this).attr('data-remitente');
      var _archivo = $(this).attr('data-archivo');
      var _nombre_archivo = $(this).attr('data-nombre-archivo');
      var _id = $(this).attr('data-id');
      $("#asuntoo").text("Asunto: " + _asunto);
      $("#contenidoo").text(_contenido) ;
      $("#modal-title").text("Mensaje de " + _remitente)
      $("#archivo").text(_nombre_archivo)
      $("#archivo").attr("href", _archivo)

        $.ajax({
          type:'GET',
          url:'/message/read/' + _id + "/",
        success: function(){
        }
      });

    });

  });
</script> 
{% endblock  %}

message/templates/msg_new.html
{% extends "msg_index.html" %}

{% block msj %}
		<div class="row">
		   	<div id="navbar" class="navbar-collapse collapse">
          		<ul class="nav navbar-nav navbar-left">
					<li><h4><span class="fa fa-envelope pull-left"></span>Nuevo mensaje</h4></li>
              	</ul>
			</div>
			<div class="form-group">
				<input type="text" placeholder="Escribe un nombre de usuario" required class="form-control">
			</div>
				 <div class="col-md-12 col-sm-12 col-xs-12 mail-reply">
                       <textarea class="summernote">Type Your Message..</textarea>
                 </div>
			<div class="form-group">
				<a class="btn btn-success">Enviar</a>
				<a href="{% url 'msg_index' %}" class="btn btn-danger">Cancelar</a>
			</div>
		</div>
	
{% endblock %}